apiVersion: v1
kind: Service
metadata:
  name: helloworld-http
  namespace: thingsboard
  labels:
    app: helloworld
    version: v1
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: thingsboard
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
        - name: helloworld
          image: registry.gateway.uno/test/hello-app:1.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080