apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: thingsboard
  labels:
    app: tb-node
  name: tb-node-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi